name: ChStore
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  http: 0.12.0
  shared_preferences: 0.5.6
  flutter_bloc: 3.1.0
  equatable: 1.0.2
  faker: 1.1.1
  flutter_rating_bar: 3.0.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    # Icons
    - icon/ChStore_red.png
    - icon/ChStore_white.png
    - icon/today-icon.png
    - icon/toggle-menu-icon.png
    - icon/search-icon.png
    - icon/facebook.png
    - icon/facebook_white.png
    - icon/zalo.png
    - icon/like.png

    # Item
    - icon/pant.png
    - icon/hat.png
    - icon/bikini.png
    - icon/tie.png
    - icon/sweater.png
    - icon/t-shirt.png
    - icon/glove.png
    - icon/shoe.png

    # Bank
    - lib/picture/banking/acb.png
    - lib/picture/banking/agribank.png
    - lib/picture/banking/sacombank.png
    - lib/picture/banking/techcombank.png
    - lib/picture/banking/tpbank.jpg
    - lib/picture/banking/vietcombank.png
    - lib/picture/banking/vietinbank.png
    - lib/picture/banking/vpbank.jpg

    # Topic
    - lib/picture/topic/man-category.jpg
    - lib/picture/topic/woman-category.jpg
    - lib/picture/topic/sport-category.png

    # Category
    - lib/picture/category/sports.jpg
    - lib/picture/category/travel.jpg
    - lib/picture/category/music.jpg
    - lib/picture/category/gaming.jpg
    - lib/picture/category/photography.jpg
    - lib/picture/category/food.jpg

    # Background
    - lib/picture/background/version_1.png
    - lib/picture/background/bg1.jpg
    - lib/picture/background/bg1_header.jpg
    - lib/picture/background/bg1_body.jpg
    - lib/picture/background/bg2.jpg
    - lib/picture/background/bg3.jpg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
